### PR TITLE
Some improvements mybe?

### PR DESCRIPTION
**Pull request by JastinXyz**
Fixed descriptions with correct descriptions, Codeblock formatting and syntax highlighting, Some examples on functions (if I did it right I might continue)

gw ngomong apa sih njir

### CODE REVIEW

**Comment by FightFarewellFearless** [comment]
gg

**Comment by JastinXyz** [comment]
> gg

klo deskripsi functionnya di keatasin gimana? kek https://jastinlinggar.gitbook.io/simpler-discord/functions/authoravatar

**Comment by JastinXyz** [comment]
eh btw ini orang indo kan?

**Comment by FightFarewellFearless** [comment]
iya

**Comment by FightFarewellFearless** [comment]
> > gg
> 
> klo deskripsi functionnya di keatasin gimana? kek https://jastinlinggar.gitbook.io/simpler-discord/functions/authoravatar

boleh

**Comment by FightFarewellFearless** [comment]
kok bisa nyasar ke sini bang 😅

**Pull request merged**
